"""Update field names in Article

Revision ID: dbefb6e62384
Revises: aa426509f985
Create Date: 2024-04-26 14:40:47.218443

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dbefb6e62384'
down_revision = 'aa426509f985'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('author', sa.Integer(), nullable=False))
        batch_op.drop_constraint('article_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['author'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('content')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('content', mysql.TEXT(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('article_ibfk_1', 'user', ['user_id'], ['id'])
        batch_op.drop_column('author')
        batch_op.drop_column('text')

    # ### end Alembic commands ###
