"""Added title to Article

Revision ID: e72f997ca3a7
Revises: 5585518de3d8
Create Date: 2024-04-30 15:47:16.559226

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e72f997ca3a7'
down_revision = '5585518de3d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=255), nullable=False))
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('title')

    # ### end Alembic commands ###
